### ISSUE TITLE
Write File Record incorrect length

### ISSUE THREAD

**Issue by jpcturbo** [dresende/node-modbus-pdu#6]
Going from modbus-pdu 0.3.1 to 1.12.0, now the record length in the message's write header is in bytes which is two times too long.  Using pdu 0.3.1 I was supplying the length as the number of words thus end represented the # of words.  Now modbus-pdu\lib\protocol\WRITE_FILE_RECORD.js is taking the length of the values array and multiplying it by two.  I believe that multiplication is unneeded.

**Comment by dresende** [comment]
You mean, the request data length is correct (in bytes), but then the records lengths should be in "registers" (16 bit) and not bytes.
